//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NfseProducaoReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.bhiss.pbh.gov.br", ConfigurationName="NfseProducaoReference.nfse")]
    public interface nfse
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.bhiss.pbh.gov.br/CancelarNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<NfseProducaoReference.CancelarNfseResponse> CancelarNfseAsync(NfseProducaoReference.CancelarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.bhiss.pbh.gov.br/ConsultarLoteRps", ReplyAction="*")]
        System.Threading.Tasks.Task<NfseProducaoReference.ConsultarLoteRpsResponse> ConsultarLoteRpsAsync(NfseProducaoReference.ConsultarLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.bhiss.pbh.gov.br/ConsultarNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<NfseProducaoReference.ConsultarNfseResponse> ConsultarNfseAsync(NfseProducaoReference.ConsultarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.bhiss.pbh.gov.br/ConsultarNfsePorFaixa", ReplyAction="*")]
        System.Threading.Tasks.Task<NfseProducaoReference.ConsultarNfsePorFaixaResponse> ConsultarNfsePorFaixaAsync(NfseProducaoReference.ConsultarNfsePorFaixaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.bhiss.pbh.gov.br/ConsultarNfsePorRps", ReplyAction="*")]
        System.Threading.Tasks.Task<NfseProducaoReference.ConsultarNfsePorRpsResponse> ConsultarNfsePorRpsAsync(NfseProducaoReference.ConsultarNfsePorRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.bhiss.pbh.gov.br/ConsultarSituacaoLoteRps", ReplyAction="*")]
        System.Threading.Tasks.Task<NfseProducaoReference.ConsultarSituacaoLoteRpsResponse> ConsultarSituacaoLoteRpsAsync(NfseProducaoReference.ConsultarSituacaoLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.bhiss.pbh.gov.br/RecepcionarLoteRps", ReplyAction="*")]
        System.Threading.Tasks.Task<NfseProducaoReference.RecepcionarLoteRpsResponse> RecepcionarLoteRpsAsync(NfseProducaoReference.RecepcionarLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.bhiss.pbh.gov.br/GerarNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<NfseProducaoReference.GerarNfseResponse> GerarNfseAsync(NfseProducaoReference.GerarNfseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarNfseRequest", WrapperNamespace="http://ws.bhiss.pbh.gov.br", IsWrapped=true)]
    public partial class CancelarNfseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public CancelarNfseRequest()
        {
        }
        
        public CancelarNfseRequest(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarNfseResponse", WrapperNamespace="http://ws.bhiss.pbh.gov.br", IsWrapped=true)]
    public partial class CancelarNfseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public CancelarNfseResponse()
        {
        }
        
        public CancelarNfseResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarLoteRpsRequest", WrapperNamespace="http://ws.bhiss.pbh.gov.br", IsWrapped=true)]
    public partial class ConsultarLoteRpsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarLoteRpsRequest()
        {
        }
        
        public ConsultarLoteRpsRequest(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarLoteRpsResponse", WrapperNamespace="http://ws.bhiss.pbh.gov.br", IsWrapped=true)]
    public partial class ConsultarLoteRpsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarLoteRpsResponse()
        {
        }
        
        public ConsultarLoteRpsResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseRequest", WrapperNamespace="http://ws.bhiss.pbh.gov.br", IsWrapped=true)]
    public partial class ConsultarNfseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfseRequest()
        {
        }
        
        public ConsultarNfseRequest(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseResponse", WrapperNamespace="http://ws.bhiss.pbh.gov.br", IsWrapped=true)]
    public partial class ConsultarNfseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarNfseResponse()
        {
        }
        
        public ConsultarNfseResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorFaixaRequest", WrapperNamespace="http://ws.bhiss.pbh.gov.br", IsWrapped=true)]
    public partial class ConsultarNfsePorFaixaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfsePorFaixaRequest()
        {
        }
        
        public ConsultarNfsePorFaixaRequest(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorFaixaResponse", WrapperNamespace="http://ws.bhiss.pbh.gov.br", IsWrapped=true)]
    public partial class ConsultarNfsePorFaixaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarNfsePorFaixaResponse()
        {
        }
        
        public ConsultarNfsePorFaixaResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorRpsRequest", WrapperNamespace="http://ws.bhiss.pbh.gov.br", IsWrapped=true)]
    public partial class ConsultarNfsePorRpsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfsePorRpsRequest()
        {
        }
        
        public ConsultarNfsePorRpsRequest(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorRpsResponse", WrapperNamespace="http://ws.bhiss.pbh.gov.br", IsWrapped=true)]
    public partial class ConsultarNfsePorRpsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarNfsePorRpsResponse()
        {
        }
        
        public ConsultarNfsePorRpsResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarSituacaoLoteRpsRequest", WrapperNamespace="http://ws.bhiss.pbh.gov.br", IsWrapped=true)]
    public partial class ConsultarSituacaoLoteRpsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarSituacaoLoteRpsRequest()
        {
        }
        
        public ConsultarSituacaoLoteRpsRequest(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarSituacaoLoteRpsResponse", WrapperNamespace="http://ws.bhiss.pbh.gov.br", IsWrapped=true)]
    public partial class ConsultarSituacaoLoteRpsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarSituacaoLoteRpsResponse()
        {
        }
        
        public ConsultarSituacaoLoteRpsResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsRequest", WrapperNamespace="http://ws.bhiss.pbh.gov.br", IsWrapped=true)]
    public partial class RecepcionarLoteRpsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public RecepcionarLoteRpsRequest()
        {
        }
        
        public RecepcionarLoteRpsRequest(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsResponse", WrapperNamespace="http://ws.bhiss.pbh.gov.br", IsWrapped=true)]
    public partial class RecepcionarLoteRpsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public RecepcionarLoteRpsResponse()
        {
        }
        
        public RecepcionarLoteRpsResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GerarNfseRequest", WrapperNamespace="http://ws.bhiss.pbh.gov.br", IsWrapped=true)]
    public partial class GerarNfseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public GerarNfseRequest()
        {
        }
        
        public GerarNfseRequest(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GerarNfseResponse", WrapperNamespace="http://ws.bhiss.pbh.gov.br", IsWrapped=true)]
    public partial class GerarNfseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public GerarNfseResponse()
        {
        }
        
        public GerarNfseResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface nfseChannel : NfseProducaoReference.nfse, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class nfseClient : System.ServiceModel.ClientBase<NfseProducaoReference.nfse>, NfseProducaoReference.nfse
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public nfseClient() : 
                base(nfseClient.GetDefaultBinding(), nfseClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.nfseSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public nfseClient(EndpointConfiguration endpointConfiguration) : 
                base(nfseClient.GetBindingForEndpoint(endpointConfiguration), nfseClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public nfseClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(nfseClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public nfseClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(nfseClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public nfseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NfseProducaoReference.CancelarNfseResponse> NfseProducaoReference.nfse.CancelarNfseAsync(NfseProducaoReference.CancelarNfseRequest request)
        {
            return base.Channel.CancelarNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<NfseProducaoReference.CancelarNfseResponse> CancelarNfseAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            NfseProducaoReference.CancelarNfseRequest inValue = new NfseProducaoReference.CancelarNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NfseProducaoReference.nfse)(this)).CancelarNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NfseProducaoReference.ConsultarLoteRpsResponse> NfseProducaoReference.nfse.ConsultarLoteRpsAsync(NfseProducaoReference.ConsultarLoteRpsRequest request)
        {
            return base.Channel.ConsultarLoteRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NfseProducaoReference.ConsultarLoteRpsResponse> ConsultarLoteRpsAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            NfseProducaoReference.ConsultarLoteRpsRequest inValue = new NfseProducaoReference.ConsultarLoteRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NfseProducaoReference.nfse)(this)).ConsultarLoteRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NfseProducaoReference.ConsultarNfseResponse> NfseProducaoReference.nfse.ConsultarNfseAsync(NfseProducaoReference.ConsultarNfseRequest request)
        {
            return base.Channel.ConsultarNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<NfseProducaoReference.ConsultarNfseResponse> ConsultarNfseAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            NfseProducaoReference.ConsultarNfseRequest inValue = new NfseProducaoReference.ConsultarNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NfseProducaoReference.nfse)(this)).ConsultarNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NfseProducaoReference.ConsultarNfsePorFaixaResponse> NfseProducaoReference.nfse.ConsultarNfsePorFaixaAsync(NfseProducaoReference.ConsultarNfsePorFaixaRequest request)
        {
            return base.Channel.ConsultarNfsePorFaixaAsync(request);
        }
        
        public System.Threading.Tasks.Task<NfseProducaoReference.ConsultarNfsePorFaixaResponse> ConsultarNfsePorFaixaAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            NfseProducaoReference.ConsultarNfsePorFaixaRequest inValue = new NfseProducaoReference.ConsultarNfsePorFaixaRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NfseProducaoReference.nfse)(this)).ConsultarNfsePorFaixaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NfseProducaoReference.ConsultarNfsePorRpsResponse> NfseProducaoReference.nfse.ConsultarNfsePorRpsAsync(NfseProducaoReference.ConsultarNfsePorRpsRequest request)
        {
            return base.Channel.ConsultarNfsePorRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NfseProducaoReference.ConsultarNfsePorRpsResponse> ConsultarNfsePorRpsAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            NfseProducaoReference.ConsultarNfsePorRpsRequest inValue = new NfseProducaoReference.ConsultarNfsePorRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NfseProducaoReference.nfse)(this)).ConsultarNfsePorRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NfseProducaoReference.ConsultarSituacaoLoteRpsResponse> NfseProducaoReference.nfse.ConsultarSituacaoLoteRpsAsync(NfseProducaoReference.ConsultarSituacaoLoteRpsRequest request)
        {
            return base.Channel.ConsultarSituacaoLoteRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NfseProducaoReference.ConsultarSituacaoLoteRpsResponse> ConsultarSituacaoLoteRpsAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            NfseProducaoReference.ConsultarSituacaoLoteRpsRequest inValue = new NfseProducaoReference.ConsultarSituacaoLoteRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NfseProducaoReference.nfse)(this)).ConsultarSituacaoLoteRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NfseProducaoReference.RecepcionarLoteRpsResponse> NfseProducaoReference.nfse.RecepcionarLoteRpsAsync(NfseProducaoReference.RecepcionarLoteRpsRequest request)
        {
            return base.Channel.RecepcionarLoteRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NfseProducaoReference.RecepcionarLoteRpsResponse> RecepcionarLoteRpsAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            NfseProducaoReference.RecepcionarLoteRpsRequest inValue = new NfseProducaoReference.RecepcionarLoteRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NfseProducaoReference.nfse)(this)).RecepcionarLoteRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NfseProducaoReference.GerarNfseResponse> NfseProducaoReference.nfse.GerarNfseAsync(NfseProducaoReference.GerarNfseRequest request)
        {
            return base.Channel.GerarNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<NfseProducaoReference.GerarNfseResponse> GerarNfseAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            NfseProducaoReference.GerarNfseRequest inValue = new NfseProducaoReference.GerarNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NfseProducaoReference.nfse)(this)).GerarNfseAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.nfseSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.nfseSOAP))
            {
                return new System.ServiceModel.EndpointAddress("https://bhissdigital.pbh.gov.br/bhiss-ws/nfse");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return nfseClient.GetBindingForEndpoint(EndpointConfiguration.nfseSOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return nfseClient.GetEndpointAddress(EndpointConfiguration.nfseSOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            nfseSOAP,
        }
    }
}
